---
# Development Environment Configuration
project:
  environment: "development"

# Development-specific component settings
components:
  dns:
    provider: "cloudflare"
    staging_mode: true
    debug_enabled: true
    
  mailcow:
    ssl_staging: true
    debug_mode: true
    skip_ssl_verification: true
    
  monitoring:
    check_interval: 60  # More frequent checks in development
    debug_logging: true
    
  vps:
    skip_security_hardening: true
    allow_password_auth: true

# Development logging - more verbose
logging:
  level: "DEBUG"
  console_output: true
  file: "data/logs/development.log"

# Development security - less strict
security:
  api_key_rotation_days: 7  # Shorter rotation for testing
  password_complexity: "medium"
  session_timeout: 7200  # 2 hours
  max_failed_attempts: 10

# Development API settings
api:
  host: "127.0.0.1"
  port: 8081
  cors_enabled: true
  debug_mode: true

# Development backup settings - more frequent for testing
backup:
  schedule: "0 */6 * * *"  # Every 6 hours
  retention_days: 7
  compression: false  # Faster backups

# Development monitoring - more verbose
monitoring:
  health_check_interval: 30  # More frequent health checks
  debug_mode: true
  test_mode: true

# Development performance - optimized for responsiveness
performance:
  worker_processes: 2
  max_concurrent_tasks: 10
  cache_ttl: 300  # 5 minutes for faster development
  batch_size: 10